image: python:3.6-alpine

stages:
  - setup
  - test

variables:
  PANDOC_VERSION: "2.7"
  # pip cache directory inside project since we can only cache local items
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.pip-cache"
  PIPENV_CACHE_DIR: "${CI_PROJECT_DIR}/.pipenv-cache"
  PIPENV_VENV_IN_PROJECT: "1"
  GIT_SUBMODULE_STRATEGY: "normal"

cache: &cache
  key: default-innoconv
  paths:
    - .pipenv-cache/
    - .pip-cache/
    - .local/bin/pandoc
    - .venv

before_script:
  - export PATH="${CI_PROJECT_DIR}/.local/bin:$PATH"
  - pip install pipenv

install:
  stage: setup
  script:
    - apk add build-base
    - mkdir -p .local
    - "[[ -e .local/bin/pandoc ]] || wget -qO- https://github.com/jgm/pandoc/releases/download/${PANDOC_VERSION}/pandoc-${PANDOC_VERSION}-linux.tar.gz | tar -xvzf - --strip-components 1 -C .local"
    - pipenv install --deploy --ignore-pipfile --dev

linting:
  stage: test
  script: pipenv run lint
  cache:
    <<: *cache
    paths:
      - .pip-cache/
      - .venv
    policy: pull

unit tests:
  stage: test
  script: pipenv run test
  coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+)/'
  cache:
    <<: *cache
    paths:
      - .pip-cache/
      - .venv
    policy: pull

integration tests:
  stage: test
  script: pipenv run integration_test
  cache:
    <<: *cache
    paths:
      - .local/bin/pandoc
      - .pip-cache/
      - .venv
    policy: pull
