image: python:3.6-alpine

stages:
  - setup
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - .cache/
  - venv/

# pip cache directory inside project since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

before_script:
  - python -V
  - python -m venv venv
  - source venv/bin/activate

install:
  stage: setup
  script:
    - apk add git
    - pip install -r requirements.txt
    - ./setup.py install

lint:
  stage: test
  script: ./setup.py pylint flake8

coverage:
  stage: test
  script: ./setup.py test
  coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+)/'
