image: innodoc/pyenv-alpine

stages:
  - test
  - coverage

# caching works only inside project directory
cache: &cache
  key: default-innoconv
  paths:
    - .coverage
    - .tox

variables:
  GIT_SUBMODULE_STRATEGY: "normal"

before_script:
  - source $HOME/.bash_profile

py37-unit:
  stage: test
  script: tox -e py37-unit

py37-integration:
  stage: test
  script: tox -e py37-integration

py36-unit:
  stage: test
  script: tox -e py36-unit

py36-integration:
  stage: test
  script: tox -e py36-integration

py35-unit:
  stage: test
  script: tox -e py35-unit

py35-integration:
  stage: test
  script: tox -e py35-integration

py34-unit:
  stage: test
  script: tox -e py34-unit

py34-integration:
  stage: test
  script: tox -e py34-integration

lint:
  stage: test
  script: tox -e lint
  cache:
    <<: *cache
    policy: pull

doc:
  stage: test
  script: tox -e doc
  cache:
    <<: *cache
    policy: pull

coverage:
  stage: coverage
  script: tox -e coverage-report
  cache:
    <<: *cache
    policy: pull
