image: innodoc/innoconv-ci

stages:
  - test
  - release

cache: &cache
  key: "${CI_PROJECT_ID}-default"
  paths:
    - .pip-cache
    - .tox

variables:
  GIT_SUBMODULE_STRATEGY: "recursive"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

before_script:
  - source $HOME/.bash_profile

py37-unit:
  stage: test
  script: tox -e py37-unit
  coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+)/'

py37-integration:
  stage: test
  script: tox -e py37-integration

py36-unit:
  stage: test
  script: tox -e py36-unit

py36-integration:
  stage: test
  script: tox -e py36-integration

py35-unit:
  stage: test
  script: tox -e py35-unit

py35-integration:
  stage: test
  script: tox -e py35-integration

py34-unit:
  stage: test
  script: tox -e py34-unit

py34-integration:
  stage: test
  script: tox -e py34-integration

lint:
  stage: test
  script: tox -e linters
  cache:
    <<: *cache
    policy: pull

doc:
  stage: test
  script: tox -e docs
  cache:
    <<: *cache
    policy: pull

pypi-upload:
  stage: release
  script:
    - if echo "$CI_COMMIT_TAG" | grep -qvE "$SEMVER_REGEXP"; then echo "Not a semver tag. Happily skipping..."; exit 0; fi
    - tox -e release
  variables:
    SEMVER_REGEXP: '^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$'
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  only:
    - tags
