image: python:3.6-alpine

stages:
  - setup
  - test

cache: &cache
  key: default-innoconv
  paths:
    - .pip-cache/
    - venv/
    - .local/

variables:
  PANDOC_VERSION: "2.3"
  # pip cache directory inside project since we can only cache local items
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.pip-cache"

before_script:
  - export PATH="${CI_PROJECT_DIR}/.local/bin:$PATH"

install:
  stage: setup
  script:
    - apk add build-base
    - mkdir -p .local
    - "[[ -e .local/bin/pandoc ]] || wget -qO- https://github.com/jgm/pandoc/releases/download/${PANDOC_VERSION}/pandoc-${PANDOC_VERSION}-linux.tar.gz | tar -xvzf - --strip-components 1 -C .local"
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip setuptools
    - pip install -r requirements.txt
    - ./setup.py install

linting:
  stage: test
  script:
    - source venv/bin/activate
    - ./setup.py lint
  cache:
    <<: *cache
    paths:
      - venv/
    policy: pull

unit tests:
  stage: test
  script:
    - source venv/bin/activate
    - ./setup.py test
  coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+)/'
  cache:
    paths:
      - venv/
    policy: pull

integration tests:
  stage: test
  script:
    - apk install git
    - source venv/bin/activate
    - ./setup.py integration_test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - venv/
      - .local/
    policy: pull
