image: python:3.6-alpine

stages:
  - setup
  - test

cache: &cache
  key: default-innoconv
  paths:
    - .pip-cache/
    - venv/
    - .local/

variables:
  PANDOC_VERSION: "2.5"
  # pip cache directory inside project since we can only cache local items
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.pip-cache"
  GIT_SUBMODULE_STRATEGY: "normal"

before_script:
  - export PATH="${CI_PROJECT_DIR}/.local/bin:$PATH"

install:
  stage: setup
  script:
    - ./.ci_install.sh
    - ./setup.py install

linting:
  stage: test
  script:
    - source venv/bin/activate
    - ./setup.py lint
  cache:
    <<: *cache
    paths:
      - venv/
    policy: pull

unit tests:
  stage: test
  script:
    - source venv/bin/activate
    - ./setup.py test
  coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+)/'
  cache:
    <<: *cache
    paths:
      - venv/
    policy: pull

integration tests:
  stage: test
  script:
    - ./.ci_install.sh
    - source venv/bin/activate
    - ./setup.py integration_test
  cache:
    <<: *cache
    paths:
      - venv/
      - .local/
    policy: pull
