image: python:alpine

stages:
  - setup
  - test

cache: &cache
  key: default-innoconv
  paths:
    - .pip-cache/
    - .local/bin/pandoc
    - .local/share/virtualenvs/

variables:
  PANDOC_VERSION: "2.7"
  # pip cache directory inside project since we can only cache local items
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.pip-cache"
  GIT_SUBMODULE_STRATEGY: "normal"

before_script:
  - export PATH="${CI_PROJECT_DIR}/.local/bin:$PATH"

install:
  stage: setup
  script:
    - apk add build-base
    - mkdir -p .local
    - "[[ -e .local/bin/pandoc ]] || wget -qO- https://github.com/jgm/pandoc/releases/download/${PANDOC_VERSION}/pandoc-${PANDOC_VERSION}-linux.tar.gz | tar -xvzf - --strip-components 1 -C .local"
    - pip install pipenv
    - pipenv sync --dev
    - ./setup.py install

linting:
  stage: test
  script: pipenv run lint
  cache:
    <<: *cache
    paths:
      - .local/share/virtualenvs/
    policy: pull

unit tests:
  stage: test
  script: pipenv run test
  coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+)/'
  cache:
    <<: *cache
    paths:
      - .local/share/virtualenvs/
    policy: pull

integration tests:
  stage: test
  script: pipenv run integration_test
  cache:
    <<: *cache
    paths:
      - .local/bin/pandoc
      - .local/share/virtualenvs/
    policy: pull
