image: python:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - ~/.cache/pip/

before_script:
  - python -V # Print out python version for debugging
  - pandoc --version
  # Uncomment next line if your Django app needs a JS runtime:
  # - apt-get update -q && apt-get install nodejs -yqq
  - apt-get install pandoc
  - pip install -r requirements.txt

test:
  script:
  - python setup.py test
