image: python:3.6-alpine

stages:
  - setup
  - test

cache: &cache
  key: default-innoconv
  paths:
    - .pip-cache/
    - venv/
    - .local/

variables:
  PANDOC_VERSION: "2.5"
  # pip cache directory inside project since we can only cache local items
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.pip-cache"
  GIT_SUBMODULE_STRATEGY: "normal"

before_script:
  - export PATH="${CI_PROJECT_DIR}/.local/bin:$PATH"

install:
  stage: setup
  script:
    - apk add build-base
    - apk add texlive
    - which pdflatex
    - stat `which pdflatex`
    - pdflatex --version
    - wget http://mirrors.ctan.org/macros/latex/contrib/ydoc.zip
    - unzip ydoc.zip
    - cd ydoc
    - tex ydoc.dtx
    - cd ..
    - wget http://mirrors.ctan.org/macros/latex/contrib/standalone.zip
    - unzip standalone.zip
    - mv ydoc/* standalone/
    - cd standalone
    - latex standalone.ins
    - cd ..
    - mkdir ~/texmf
    - mv standalone/* ~/texmf/
    - texhash ~/texmf --verbose
    - kpsewhich --show-path tex
    - kpsewhich .tex
    - kpsewhich standalone
    - mkdir -p .local
    - "[[ -e .local/bin/pandoc ]] || wget -qO- https://github.com/jgm/pandoc/releases/download/${PANDOC_VERSION}/pandoc-${PANDOC_VERSION}-linux.tar.gz | tar -xvzf - --strip-components 1 -C .local"
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip setuptools
    - pip install -r requirements.txt
    - ./setup.py install

linting:
  stage: test
  script:
    - source venv/bin/activate
    - ./setup.py lint
  cache:
    <<: *cache
    paths:
      - venv/
    policy: pull

unit tests:
  stage: test
  script:
    - apk add texlive
    - pdflatex --version
    - source venv/bin/activate
    - ./setup.py test
  coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+)/'
  cache:
    <<: *cache
    paths:
      - venv/
    policy: pull

integration tests:
  stage: test
  script:
    - apk add texlive
    - pdflatex --version
    - wget http://mirrors.ctan.org/macros/latex/contrib/ydoc.zip
    - unzip ydoc.zip
    - cd ydoc
    - tex ydoc.dtx
    - cd ..
    - wget http://mirrors.ctan.org/macros/latex/contrib/standalone.zip
    - unzip standalone.zip
    - mv ydoc/* standalone/
    - cd standalone
    - latex standalone.ins
    - cd ..
    - texhash standalone --verbose
    - source venv/bin/activate
    - ./setup.py integration_test
  cache:
    <<: *cache
    paths:
      - venv/
      - .local/
    policy: pull
