image: innodoc/pyenv-alpine

stages:
  - test

# caching works only inside project directory
cache: &cache
  key: default-innoconv
  paths:
    - .pip-cache/

variables:
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.pip-cache"
  GIT_SUBMODULE_STRATEGY: "normal"

before_script:
  - source $HOME/.bash_profile

tox:
  stage: test
  script: tox
