image: python:alpine

stages:
  - test
  - release

cache: &cache
  key: "${CI_PROJECT_ID}-default"
  paths:
    - .pip-cache
    - .tox
    - .local

variables:
  PANDOC_VERSION: "2.7"
  PDF2SVG_VERSION: "0.2.3"
  GIT_SUBMODULE_STRATEGY: "recursive"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

before_script:
  - apk add --no-cache texlive-full
  - >
    if [ ! -f .local/bin/pandoc ]; then
      mkdir -p .local/bin
      wget -qO- https://github.com/jgm/pandoc/releases/download/${PANDOC_VERSION}/pandoc-${PANDOC_VERSION}-linux.tar.gz | tar -xzf - --strip-components 2 -C .local/bin pandoc-${PANDOC_VERSION}/bin/pandoc
    fi
  - >
    if [ ! -f .local/bin/pdf2svg ]; then
      apk add --no-cache build-base cairo-dev poppler-dev
      wget -qO- https://github.com/dawbarton/pdf2svg/archive/v${PDF2SVG_VERSION}.tar.gz | tar -xzf - -C /tmp
      cd /tmp/pdf2svg-${PDF2SVG_VERSION}
      ./configure --prefix="${CI_PROJECT_DIR}/.local"
      make
      strip pdf2svg
      make install
    fi
  - export PATH="${CI_PROJECT_DIR}/.local/bin:$PATH"
  - pip install tox

py37-unit:
  stage: test
  image: python:3.7-alpine
  script: tox -e py37-unit
  coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+)/'

py37-integration:
  stage: test
  image: python:3.7-alpine
  script: tox -e py37-integration

py36-unit:
  stage: test
  image: python:3.6-alpine
  script: tox -e py36-unit

py36-integration:
  stage: test
  image: python:3.6-alpine
  script: tox -e py36-integration

py35-unit:
  stage: test
  image: python:3.5-alpine
  script: tox -e py35-unit

py35-integration:
  stage: test
  image: python:3.5-alpine
  script: tox -e py35-integration

py34-unit:
  stage: test
  image: python:3.4-alpine
  script: tox -e py34-unit

py34-integration:
  stage: test
  image: python:3.4-alpine
  script: tox -e py34-integration

lint:
  stage: test
  image: python:3.7-alpine
  script: tox -e lint
  cache:
    <<: *cache
    policy: pull

doc:
  stage: test
  image: python:3.7-alpine
  script: tox -e doc
  cache:
    <<: *cache
    policy: pull

pypi-upload:
  stage: release
  image: python:3.7-alpine
  script:
    - if echo "$CI_COMMIT_TAG" | grep -qvE "$SEMVER_REGEXP"; then echo "Not a semver tag. Happily skipping..."; exit 0; fi
    - tox -e release
  variables:
    SEMVER_REGEXP: '^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$'
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  only:
    - tags
