image: python:3.6-alpine

stages:
  - setup
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - .pip-cache/
  - venv/
  - .local/

# pip cache directory inside project since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

before_script:
  - python -m venv venv
  - export PATH="$CI_PROJECT_DIR/.local/bin:$PATH"
  - source venv/bin/activate

install:
  stage: setup
  script:
    - "which git || apk add git"
    - mkdir -p .local
    - "which pandoc || wget -qO- https://github.com/jgm/pandoc/releases/download/2.2.2.1/pandoc-2.2.2.1-linux.tar.gz | tar -xzf - --strip-components 1 -C .local"
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - ./setup.py install

lint:
  stage: test
  script: ./setup.py lint
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - venv/
# TODO: Add this when GitLab is upgraded!
#    policy: pull  ADD when GitLab is upgraded!

coverage:
  stage: test
  script:
    - mkdir -p ~/.panzer
    - echo $PATH
    - find .local
    - ls -la
    - ./setup.py test
  coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+)/'
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - venv/
      - .local/
# TODO: Add this when GitLab is upgraded!
#  cache:
#    policy: pull
