image: python:3.6-alpine

stages:
  - setup
  - test

cache: &cache
  key: innoconv-default
  paths:
    - .pip-cache/
    - venv/
    - .local/

variables:
  PANDOC_VERSION: "2.3"
  # pip cache directory inside project since we can only cache local items
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

before_script:
  - mkdir -p .local
  - python -m venv venv
  - export PATH="$CI_PROJECT_DIR/.local/bin:$PATH"
  - source venv/bin/activate

install:
  stage: setup
  script:
    - apk add build-base
    - wget -qO- https://github.com/jgm/pandoc/releases/download/${PANDOC_VERSION}/pandoc-${PANDOC_VERSION}-linux.tar.gz | tar -xvzf - --strip-components 1 -C .local
    - pip install --upgrade pip setuptools
    - pip install -r requirements.txt
    - ./setup.py install
    - ls -l venv/bin/green

linting:
  stage: test
  script:
    - ./setup.py lint
    - ls -l venv/bin/green
  cache:
    <<: *cache
    policy: pull

unit tests:
  stage: test
  script:
    - ls -l venv/bin/green
    - ./setup.py test
  coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+)/'
  cache:
    <<: *cache
    policy: pull

integration tests:
  stage: test
  script:
    - ls -l venv/bin/green
    - ./setup.py integration_test
  cache:
    <<: *cache
    policy: pull
